import { useMemo, useState, type ReactNode } from 'react'
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useParams, useSearchParams } from 'react-router-dom'
import { EnterRankingDialog } from '../features/creator-entry/ui/EnterRankingDialog'
import { rankCreators } from '../features/leaderboard/application/rankCreators'
import { dummyCreators } from '../features/leaderboard/data/dummyCreators'
import { creatorCategories, creatorCategoryLabels, type Creator, type CreatorCategory, type RankedCreator } from '../features/leaderboard/domain/creator'
import { RankingList } from '../features/leaderboard/ui/RankingList'
import { BoostDialog } from '../features/payments/ui/BoostDialog'
import { appServices } from '../shared/config/appServices'
import { formatCurrency } from '../shared/format/currency'

function Layout({ children, onEnter }: { children: ReactNode; onEnter: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false)
  return <><header className="site-header"><nav className="nav"><Link className="brand" to="/"><span>♛</span>CrownRank</Link><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">☰</button><div className={`nav-actions ${menuOpen ? 'open' : ''}`}><NavLink to="/">Home</NavLink><NavLink to="/rankings">Global rank</NavLink><NavLink to="/daily">Daily rank</NavLink><NavLink to="/categories">Categories</NavLink><NavLink to="/about">About</NavLink><NavLink to="/rules">Rules</NavLink><button className="primary-button compact" onClick={onEnter}>Enter ranking</button></div></nav></header><main>{children}</main><footer><Link className="brand" to="/"><span>♛</span>CrownRank</Link><div className="footer-links"><Link to="/about">About</Link><Link to="/rules">Rules</Link><Link to="/terms">Terms</Link><Link to="/privacy">Privacy</Link></div><span>© 2026 CrownRank</span></footer></>
}

function CategoryFilter({ value, onChange }: { value: CreatorCategory | 'all'; onChange: (value: CreatorCategory | 'all') => void }) {
  return <label className="filter-select"><span>Category</span><select value={value} onChange={(e) => onChange(e.target.value as CreatorCategory | 'all')}><option value="all">All creators</option>{creatorCategories.map(category => <option value={category} key={category}>{creatorCategoryLabels[category]}</option>)}</select></label>
}

function BoardHeader({ eyebrow, title, copy, control }: { eyebrow: string; title: string; copy: string; control?: ReactNode }) {
  return <div className="board-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{control}</div>
}

function Home({ ranked, onBoost, onEnter }: { ranked: readonly RankedCreator[]; onBoost: (c: Creator) => void; onEnter: () => void }) {
  const [limit, setLimit] = useState(5)
  return <>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">The fan-powered creator leaderboard</p><h1>Rise through the ranks.<br /><span>Claim the crown.</span></h1><p className="intro">Creators enter with any amount. Communities boost who they believe in. Every score is visible.</p><div className="hero-actions"><button className="primary-button large" onClick={onEnter}>Enter the ranking <span>→</span></button><Link to="/rankings">View global rank</Link></div><div className="trust-row"><span>No account required</span><span>Any starting amount</span><span>Transparent ranking</span></div></div><div className="crown-card"><span className="mini-label">Current world #1</span><img src={ranked[0].imageUrl} alt="" /><strong>{ranked[0].displayName}</strong><small>@{ranked[0].username}</small><b>{formatCurrency(ranked[0].totalContributedCents)}</b></div></section>
    <section className="board-section"><div className="section-heading"><div><p className="eyebrow">Global ranking</p><h2>Top creators worldwide</h2></div><Link to="/rankings">Full ranking →</Link></div><RankingList creators={ranked.slice(0, limit)} onBoost={onBoost} compact />{limit === 5 ? <button className="secondary-button board-more" onClick={() => setLimit(10)}>See top 10</button> : <Link className="secondary-button board-more" to="/rankings">See full ranking</Link>}</section>
    <section className="daily-preview"><div><p className="eyebrow">Today’s leaders</p><h2>Who is rising today?</h2><p>Daily scores reset at midnight UTC, giving every creator a fresh chance to lead.</p><Link className="text-link" to="/daily">See daily ranking →</Link></div><RankingList creators={ranked.slice().sort((a,b) => b.dailyContributedCents-a.dailyContributedCents).slice(0,3).map((c,i) => ({...c, rank:i+1, totalContributedCents:c.dailyContributedCents}))} onBoost={onBoost} compact /></section>
  </>
}

function Rankings({ ranked, onBoost }: { ranked: readonly RankedCreator[]; onBoost: (c: Creator) => void }) {
  const [params, setParams] = useSearchParams()
  const category = (params.get('category') ?? 'all') as CreatorCategory | 'all'
  const page = Math.max(1, Number(params.get('page') ?? 1))
  const filtered = category === 'all' ? ranked : ranked.filter(c => c.category === category)
  const pageSize = 25, pages = Math.max(1, Math.ceil(filtered.length / pageSize))
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize)
  return <section className="page-shell"><BoardHeader eyebrow="All-time leaderboard" title="Global ranking" copy="The complete CrownRank board, ordered by total confirmed contributions." control={<CategoryFilter value={category} onChange={(next) => setParams(next === 'all' ? {} : { category: next })} />} /><RankingList creators={visible} onBoost={onBoost} /><nav className="pagination" aria-label="Ranking pages"><button disabled={page <= 1} onClick={() => setParams({ ...(category !== 'all' && { category }), page: String(page - 1) })}>← Previous</button><span>Page {Math.min(page,pages)} of {pages}</span><button disabled={page >= pages} onClick={() => setParams({ ...(category !== 'all' && { category }), page: String(page + 1) })}>Next →</button></nav></section>
}

const dateKey = (date: Date) => date.toISOString().slice(0, 10)
const todayKey = () => dateKey(new Date())
const archivedDateKeys = () => Array.from({ length: 14 }, (_, index) => { const date = new Date(); date.setUTCDate(date.getUTCDate() - index); return dateKey(date) })
const dailyScore = (creator: RankedCreator, date: string) => {
  const seed = [...`${creator.id}-${date}`].reduce((total, character) => total + character.charCodeAt(0), 0)
  return Math.max(100, Math.round((creator.dailyContributedCents * (55 + seed % 91)) / 100))
}

function Daily({ ranked, onBoost, onEnter }: { ranked: readonly RankedCreator[]; onBoost: (c: Creator) => void; onEnter: () => void }) {
  const { date } = useParams()
  const selectedDate = date && archivedDateKeys().includes(date) ? date : todayKey()
  const isToday = selectedDate === todayKey()
  const [category, setCategory] = useState<CreatorCategory | 'all'>('all')
  const daily = useMemo(() => ranked.filter(c => category === 'all' || c.category === category).map(c => ({ ...c, totalContributedCents: isToday ? c.dailyContributedCents : dailyScore(c, selectedDate) })).sort((a,b) => b.totalContributedCents-a.totalContributedCents).map((c,i) => ({...c, rank:i+1})), [ranked, category, isToday, selectedDate])
  return <section className="page-shell"><BoardHeader eyebrow={isToday ? 'Live · resets at 00:00 UTC' : 'Daily archive'} title={isToday ? 'Today’s ranking' : new Date(`${selectedDate}T12:00:00Z`).toLocaleDateString('en-GB', { weekday:'long', day:'numeric', month:'long', year:'numeric' })} copy={isToday ? 'See every creator receiving support today, or revisit the leaders from a previous date.' : 'The final daily standings recorded for this date.'} control={<CategoryFilter value={category} onChange={setCategory} />} /><div className="daily-toolbar"><div className="date-strip" aria-label="Choose ranking date">{archivedDateKeys().slice(0,7).map(key => <Link className={key === selectedDate ? 'selected' : ''} to={key === todayKey() ? '/daily' : `/daily/${key}`} key={key}><b>{key === todayKey() ? 'Today' : new Date(`${key}T12:00:00Z`).toLocaleDateString('en-GB',{weekday:'short'})}</b><span>{new Date(`${key}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span></Link>)}</div>{isToday && <button className="primary-button compact" onClick={onEnter}>Rank up</button>}</div><RankingList creators={daily} onBoost={onBoost} /><DailyArchive dates={archivedDateKeys().slice(1)} selectedDate={selectedDate} /></section>
}

function DailyArchive({ dates, selectedDate }: { dates: readonly string[]; selectedDate: string }) {
  return <section className="archive-section"><div><p className="eyebrow">Past results</p><h2>Daily archive</h2></div><div className="archive-grid">{dates.map(date => <Link className={date === selectedDate ? 'selected' : ''} to={`/daily/${date}`} key={date}><span>{new Date(`${date}T12:00:00Z`).toLocaleDateString('en-GB',{weekday:'long'})}</span><strong>{new Date(`${date}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</strong><small>Show all →</small></Link>)}</div></section>
}

function InformationPage({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: ReactNode }) {
  return <article className="content-page"><header><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></header><div className="prose">{children}</div></article>
}

function About() { return <InformationPage eyebrow="About CrownRank" title="A visible stage for creator support." intro="CrownRank is a public, community-powered leaderboard where creators can enter and anyone can help them rise—without creating an account."><h2>How it works</h2><p>A creator submits their public profile, selects a category and chooses an initial Rank Up amount. Once payment is confirmed, the profile is published automatically. Fans can then boost that creator with any eligible amount.</p><h2>Two ways to lead</h2><p>The global board reflects all confirmed contributions. The daily board starts fresh at 00:00 UTC and preserves previous results in a date-based archive.</p><h2>Built for every creator</h2><p>Streamers, gamers, educators, influencers and adult-industry creators are welcome. CrownRank itself remains safe for work: explicit imagery, nudity and sexually explicit profile content are not permitted.</p></InformationPage> }

function Rules() { return <InformationPage eyebrow="Community standards" title="CrownRank rules" intro="These rules keep rankings fair, profiles accurate and the public experience safe."><h2>1. Adults only</h2><p>You must be at least 18 years old to submit a profile, make a payment or otherwise use CrownRank.</p><h2>2. Accurate profiles</h2><p>Use truthful names, handles, categories and social links. Do not impersonate another person or submit content you have no right to use.</p><h2>3. Safe-for-work content</h2><p>Adult-industry creators may participate, but profile images and text must not include nudity, explicit sexual content, exploitation or illegal material.</p><h2>4. Fair ranking</h2><p>Do not use stolen payment methods, automated abuse, chargeback fraud or technical manipulation. Confirmed contributions determine rank; suspicious activity may be withheld, reversed or removed.</p><h2>5. Automatic publishing and moderation</h2><p>Eligible profiles publish automatically after confirmed payment. CrownRank may later edit, hide or remove any profile or link that violates these rules or creates legal or safety risk. Report concerns to <a href="mailto:parweshbhaggan@outlook.com">parweshbhaggan@outlook.com</a>.</p></InformationPage> }

function Terms() { return <InformationPage eyebrow="Legal · last updated 7 September 2026" title="Terms of agreement" intro="These terms govern your use of CrownRank and all Rank Up and Boost purchases."><h2>Operator</h2><p>CrownRank is operated by Starbolt Studios, Wilgenlei 102D, 3052 CJ Rotterdam, the Netherlands. Starbolt Studios is not yet a registered business. CrownRank must not accept live payments until its registration and legally required business disclosures are complete.</p><h2>Eligibility and acceptance</h2><p>You must be 18 or older. By using CrownRank or completing a payment, you accept these Terms and the Rules. No user account is created.</p><h2>Rank Up and Boost purchases</h2><p>Rank Up places an eligible creator on the leaderboard. Boost adds to a creator’s score. Amounts are selected by the payer and processed by Stripe. A displayed ranking changes as other confirmed payments are received; no particular position or duration is guaranteed.</p><h2>Publication and creator submissions</h2><p>Profiles are normally published automatically after confirmed payment. You confirm that submitted details are accurate and that you have permission to provide all names, images and links. Payment does not prevent later moderation or removal.</p><h2>Final payments</h2><p>Completed Rank Up and Boost payments are final and non-refundable, except where applicable law requires a remedy or where a payment is unauthorized, duplicated, or caused by CrownRank error. Removal of a profile does not automatically create a refund right.</p><h2>Prohibited conduct</h2><p>You may not impersonate others, infringe intellectual-property or privacy rights, submit explicit on-site content, manipulate rankings, misuse payment instruments, disrupt the service or break applicable law.</p><h2>Availability and liability</h2><p>CrownRank may change, suspend or discontinue features and correct ranking or payment errors. Nothing in these Terms excludes liability that cannot legally be excluded. To the extent permitted by law, Starbolt Studios is not responsible for indirect loss or third-party social platforms.</p><h2>Governing law</h2><p>Dutch law applies. Disputes are submitted to the competent courts of Rotterdam, except where mandatory consumer law gives you the right to bring a claim elsewhere.</p><h2>Contact</h2><p>Questions or legal notices may be sent to <a href="mailto:parweshbhaggan@outlook.com">parweshbhaggan@outlook.com</a>.</p></InformationPage> }

function Privacy() { return <InformationPage eyebrow="Legal · last updated 7 September 2026" title="Privacy policy" intro="This policy explains the personal information CrownRank uses to operate its public rankings and process payments."><h2>Controller</h2><p>Starbolt Studios, Wilgenlei 102D, 3052 CJ Rotterdam, the Netherlands, is responsible for CrownRank’s processing. Privacy requests can be sent to <a href="mailto:parweshbhaggan@outlook.com">parweshbhaggan@outlook.com</a>.</p><h2>Information we collect</h2><p>Profile submissions may include a first and last name, username, category, biography, location, profile image and public social links. We also process contribution amount, status, timestamps and technical information needed for security and service operation. Stripe receives and processes payment details; CrownRank should not store full card numbers.</p><h2>Why we use it</h2><p>We use information to publish and rank creator profiles, confirm payments, prevent fraud, moderate content, answer requests, maintain records and comply with legal obligations. Depending on the activity, the legal basis may be performance of a contract, legitimate interests, consent or a legal obligation.</p><h2>Public information</h2><p>Creator profile information, social links, category, score and ranking are public. Do not submit private contact details or information you are not authorized to publish.</p><h2>Sharing</h2><p>Information is shared with Stripe and with technical providers only as needed to deliver and secure CrownRank or meet legal requirements. CrownRank currently uses no analytics provider and does not sell personal information.</p><h2>Retention and deletion</h2><p>After a valid verified request, CrownRank will remove eligible public profile information. Transaction, tax, fraud-prevention and legal records may be retained for the period required or permitted by law. Backup copies may remain temporarily until they are safely overwritten.</p><h2>Your rights</h2><p>Subject to applicable law, you may request access, correction, deletion, restriction, portability or objection, and may complain to the Dutch Data Protection Authority. CrownRank may need to verify your identity before acting.</p><h2>International services</h2><p>Some providers may process information outside the European Economic Area using legally recognized safeguards. Provider details and safeguards must be confirmed before launch.</p><h2>Cookies</h2><p>CrownRank does not currently use analytics cookies. Essential storage may be used for security, checkout continuity and core site operation. This policy will be updated before any optional analytics or advertising technology is introduced.</p></InformationPage> }

function Categories({ ranked }: { ranked: readonly RankedCreator[] }) {
  return <section className="page-shell"><BoardHeader eyebrow="Explore CrownRank" title="Creator categories" copy="Find the leading creators in every corner of the creator economy." /><div className="category-grid">{creatorCategories.map(category => { const leaders = ranked.filter(c => c.category === category).slice(0,3); return <Link className="category-card" to={`/rankings?category=${category}`} key={category}><div><span className="category-icon">♛</span><h2>{creatorCategoryLabels[category]}</h2></div><span>{ranked.filter(c => c.category === category).length} creators</span>{leaders.length > 0 ? <ol>{leaders.map((creator,i) => <li key={creator.id}><b>#{i+1}</b><img src={creator.imageUrl} alt="" /><span>{creator.displayName}</span><strong>{formatCurrency(creator.totalContributedCents)}</strong></li>)}</ol> : <p>Be the first in this category.</p>}</Link> })}</div></section>
}

function Profile({ ranked, onBoost }: { ranked: readonly RankedCreator[]; onBoost: (c: Creator) => void }) {
  const { id } = useParams()
  const creator = ranked.find(c => c.id === id)
  if (!creator) return <Navigate to="/rankings" replace />
  return <section className="profile-page"><Link className="back-link" to="/rankings">← Back to ranking</Link><div className="profile-hero"><img src={creator.imageUrl} alt={creator.displayName} /><div className="profile-copy"><span className="category-pill">{creatorCategoryLabels[creator.category]}</span><h1>{creator.firstName} {creator.lastName}</h1><p className="profile-handle">@{creator.username}</p><p>{creator.bio}</p><div className="profile-meta"><span>📍 {creator.location}</span><span>Joined {new Date(creator.joinedAt).toLocaleDateString('en-US',{month:'long',year:'numeric'})}</span></div><div className="social-profile-links">{creator.socialProfiles.map(profile => <a href={profile.url} target="_blank" rel="noreferrer" key={profile.id}>{profile.platform} ↗</a>)}</div></div><aside className="profile-rank"><p>Global rank</p><strong>#{creator.rank}</strong><p>Total score</p><b>{formatCurrency(creator.totalContributedCents)}</b><button className="primary-button full" onClick={() => onBoost(creator)}>Boost this creator</button><small>Anyone can boost. No account needed.</small></aside></div></section>
}

export function App() {
  const ranked = useMemo(() => rankCreators(dummyCreators), [])
  const [entryOpen, setEntryOpen] = useState(false)
  const [boostCreator, setBoostCreator] = useState<Creator>()
  return <BrowserRouter><Layout onEnter={() => setEntryOpen(true)}><Routes><Route path="/" element={<Home ranked={ranked} onBoost={setBoostCreator} onEnter={() => setEntryOpen(true)} />} /><Route path="/rankings" element={<Rankings ranked={ranked} onBoost={setBoostCreator} />} /><Route path="/daily" element={<Daily ranked={ranked} onBoost={setBoostCreator} onEnter={() => setEntryOpen(true)} />} /><Route path="/daily/:date" element={<Daily ranked={ranked} onBoost={setBoostCreator} onEnter={() => setEntryOpen(true)} />} /><Route path="/categories" element={<Categories ranked={ranked} />} /><Route path="/creators/:id" element={<Profile ranked={ranked} onBoost={setBoostCreator} />} /><Route path="/about" element={<About />} /><Route path="/rules" element={<Rules />} /><Route path="/terms" element={<Terms />} /><Route path="/privacy" element={<Privacy />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Layout><EnterRankingDialog isOpen={entryOpen} paymentGateway={appServices.paymentGateway} onClose={() => setEntryOpen(false)} /><BoostDialog creator={boostCreator} gateway={appServices.paymentGateway} onClose={() => setBoostCreator(undefined)} /></BrowserRouter>
}
