<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>847f6ee9-34b6-4afc-a544-e2a305d46ac7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrownRank.Application\CrownRank.Application.csproj" />
    <ProjectReference Include="..\CrownRank.Infrastructure\CrownRank.Infrastructure.csproj" />
  </ItemGroup>

</Project>
