// <auto-generated />
using System;
using CrownRankApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable
namespace CrownRankApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930155747_BoostMigration")]
    partial class BoostMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryEntry", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntriesId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "EntriesId");

                    b.HasIndex("EntriesId");

                    b.ToTable("EntryCategories", (string)null);
                });

            modelBuilder.Entity("CrownRankApp.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Live-streaming creators and personalities.",
                            Name = "Streamer"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gaming creators, players and esports personalities.",
                            Name = "Gaming"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lifestyle and social-media personalities.",
                            Name = "Influencer"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adult-oriented creators and performers.",
                            Name = "Adult Entertainment"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Beauty, style and fashion creators.",
                            Name = "Beauty & Fashion"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness, health and wellness creators.",
                            Name = "Fitness & Wellness"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Musicians, singers, producers and DJs.",
                            Name = "Music"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Podcast hosts and audio creators.",
                            Name = "Podcasting"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Educational creators and subject-matter experts.",
                            Name = "Education"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comedians and entertainment creators.",
                            Name = "Comedy"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Artists, illustrators and designers.",
                            Name = "Art & Design"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Food, cooking and culinary creators.",
                            Name = "Food"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Travel creators and explorers.",
                            Name = "Travel"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Technology creators and reviewers.",
                            Name = "Technology"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Business, finance and entrepreneurship creators.",
                            Name = "Business"
                        },
                            new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creators who do not fit another category.",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("CrownRankApp.Domain.Models.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("CrownRankApp.Domain.Models.ScoreAddition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("CreatedDate", "EntryId");

                    b.ToTable("ScoreAdditions");
                });

            modelBuilder.Entity("CrownRankApp.Domain.Models.SocialMediaDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SocialMediaDefaults");

                    b.HasData(
                            new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Instagram"
                        },
                            new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TikTok"
                        },
                            new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "YouTube"
                        },
                            new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "OnlyFans"
                        },
                            new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Facebook"
                        },
                            new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "X"
                        },
                            new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Twitch"
                        },
                            new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Website"
                        });
                });

            modelBuilder.Entity("CrownRankApp.Domain.Models.SocialMediaPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("PlatformId");

                    b.ToTable("SocialMediaPlatforms");
                });

            modelBuilder.Entity("CategoryEntry", b =>
                {
                    b.HasOne("CrownRankApp.Domain.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrownRankApp.Domain.Models.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrownRankApp.Domain.Models.ScoreAddition", b =>
                {
                    b.HasOne("CrownRankApp.Domain.Models.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("CrownRankApp.Domain.Models.SocialMediaPlatform", b =>
                {
                    b.HasOne("CrownRankApp.Domain.Models.Entry", "Entry")
                        .WithMany("SocialMediaPlatforms")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrownRankApp.Domain.Models.SocialMediaDefault", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("CrownRankApp.Domain.Models.Entry", b =>
                {
                    b.Navigation("SocialMediaPlatforms");
                });
            #pragma warning restore 612, 618
        }
    }
}
