// <auto-generated />
using System;
using CrownRank.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrownRank.Infrastructure.Migrations
{
    [DbContext(typeof(CrownRankDbContext))]
    [Migration("20260918130829_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrownRank.Application.Payments.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long?>("ConfirmedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "State");

                    b.HasIndex("Provider", "Reference")
                        .IsUnique();

                    b.ToTable("PaymentAttempts", (string)null);
                });

            modelBuilder.Entity("CrownRank.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("CrownRank.Domain.Models.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<long?>("HiddenAtUtc")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("InitialContributionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfileImageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("PublishedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Status");

                    b.ToTable("Entries", (string)null);
                });

            modelBuilder.Entity("CrownRank.Domain.Models.RankingContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ConfirmedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ExcludedAtUtc")
                        .HasColumnType("bigint");

                    b.Property<int?>("ExclusionReason")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentProvider", "PaymentReference")
                        .IsUnique();

                    b.HasIndex("EntryId", "Status", "ConfirmedAtUtc");

                    b.ToTable("RankingContributions", (string)null);
                });

            modelBuilder.Entity("CrownRank.Application.Payments.PaymentAttempt", b =>
                {
                    b.HasOne("CrownRank.Domain.Models.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CrownRank.Domain.ValueObjects.Money", "ExpectedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentAttemptId")
                                .HasColumnType("uuid");

                            b1.Property<long>("AmountInMinorUnits")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("PaymentAttemptId");

                            b1.ToTable("PaymentAttempts");

                            b1.WithOwner()
                                .HasForeignKey("PaymentAttemptId");
                        });

                    b.Navigation("ExpectedAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("CrownRank.Domain.Models.Entry", b =>
                {
                    b.HasOne("CrownRank.Domain.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("CrownRank.Domain.Models.SocialMediaLink", "SocialMediaLinks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("CustomPlatformName")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("EntryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Platform")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");

                            b1.HasKey("Id");

                            b1.HasIndex("EntryId");

                            b1.ToTable("SocialMediaLinks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EntryId");
                        });

                    b.OwnsOne("CrownRank.Domain.ValueObjects.AgreementAcceptance", "AgreementAcceptance", b1 =>
                        {
                            b1.Property<Guid>("EntryId")
                                .HasColumnType("uuid");

                            b1.Property<long>("AcceptedAtUtc")
                                .HasColumnType("bigint");

                            b1.Property<string>("PrivacyPolicyVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("RulesVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("TermsVersion")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("EntryId");

                            b1.ToTable("Entries");

                            b1.WithOwner()
                                .HasForeignKey("EntryId");
                        });

                    b.Navigation("AgreementAcceptance")
                        .IsRequired();

                    b.Navigation("SocialMediaLinks");
                });

            modelBuilder.Entity("CrownRank.Domain.Models.RankingContribution", b =>
                {
                    b.HasOne("CrownRank.Domain.Models.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CrownRank.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RankingContributionId")
                                .HasColumnType("uuid");

                            b1.Property<long>("AmountInMinorUnits")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("RankingContributionId");

                            b1.ToTable("RankingContributions");

                            b1.WithOwner()
                                .HasForeignKey("RankingContributionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
